version: '3'
services:
  django:
    build:
      context: ./app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env
    user: "1000"
    expose:
      - 8000
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12.0-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data/
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    restart: always
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - django
    restart: always

volumes:
  static_volume: