# Generated by Django 3.1 on 2021-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='old_id',
            field=models.CharField(default='', max_length=27, unique=True, verbose_name='старый id'),
        ),
    ]
